/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#ddc39d',
        'primary-fixed': '#d8e3fb',
        'on-error-container': '#93000a',
        'on-secondary-container': '#fefcff',
        'tertiary-container': '#35260c',
        secondary: '#0058be',
        outline: '#75777d',
        'inverse-surface': '#213145',
        'on-tertiary-container': '#a38c6a',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-fixed-variant': '#3c475a',
        'surface-variant': '#d3e4fe',
        'on-primary-fixed': '#111c2d',
        background: '#f8f9ff',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        surface: '#f8f9ff',
        'on-secondary-fixed-variant': '#004395',
        'inverse-primary': '#bcc7de',
        'surface-container-highest': '#d3e4fe',
        'error-container': '#ffdad6',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45474c',
        'on-secondary-fixed': '#001a42',
        'outline-variant': '#c5c6cd',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#e5eeff',
        'on-error': '#ffffff',
        'secondary-container': '#2170e4',
        tertiary: '#1e1200',
        'surface-bright': '#f8f9ff',
        'on-primary-container': '#8590a6',
        'surface-tint': '#545f73',
        'surface-container-low': '#eff4ff',
        'surface-dim': '#cbdbf5',
        'secondary-fixed-dim': '#adc6ff',
        'on-background': '#0b1c30',
        primary: '#091426',
        'primary-container': '#1e293b',
        'on-tertiary-fixed': '#271902',
        'surface-container-high': '#dce9ff',
        'on-tertiary-fixed-variant': '#564427',
        'primary-fixed-dim': '#bcc7de',
        'secondary-fixed': '#d8e2ff',
        'tertiary-fixed': '#fadfb8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        container_padding: '32px',
        stack_md: '16px',
        gutter: '24px',
        sidebar_width: '260px',
        header_height: '64px',
        stack_sm: '8px',
        stack_lg: '24px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'data-mono': ['"JetBrains Mono"', 'monospace'],
        'body-base': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
